kind: pipeline
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build . -t cda-app:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: deploy-preview
    image: docker/compose:1.24.1
    volumes:
        - name: docker
          path: /var/run/docker.sock
    commands:
      - docker-compose up -d -p cda-app preview

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
