version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: yarn build
      - run: sudo apt install rsync
      - run: rsync ./build/ $SSH_USER@$SSH_HOST:/srv/confidences-app -p 1023
    branches:
      only:
        - master
