version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: yarn build
      - run: sudo apt install rsync
      - run: rsync -av -e 'ssh -p 1023' ./build $SSH_USER@$SSH_HOST:/srv/confidences-app
      - run: ssh $SSH_USER@$SSH_HOST -p 1023 'pm2 reload app'
    branches:
      only:
        - master
