version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: $SSH_USER@$SSH_HOST 'wall "CI in da place"'
    branches:
      only:
        - master
