version: 2
jobs:
  build:
    docker:
      - image: cypress/base:latest
        environment:
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
#            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:e2e
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
