version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/confidences-app

    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: yarn build
